CREATE TABLE sgo.tb_pessoa(
  id_pessoa INT AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT 'CÓDIGO DA PESSOA',
  nm_pessoa VARCHAR(70) NOT NULL COMMENT 'NOME DA PESSOA',
  fl_sexo	CHAR(1)	NOT NULL COMMENT 'INFORMAR M OU F',
  dt_cadastro DATETIME NOT NULL COMMENT 'DATA DE CADASTRO DO REGISTRO',
  ds_email	VARCHAR(80) NOT NULL COMMENT 'EMAIL DA PESSOA',
  ds_endereco VARCHAR(200) NOT NULL COMMENT 'DESCRIÇÃO DO ENDEREÇO',
  fl_origemCadastro CHAR(1)	NOT NULL COMMENT 'ORIGEM DO CADASTRO (I) = INPUT OU (X) = XML',
  id_usuario_cadastro	INT	NOT NULL COMMENT 'USUÁRIO LOGADO QUE CADASTROU A PESSOA'
);

ALTER TABLE sgo.tb_pessoa ADD FOREIGN KEY (id_usuario_cadastro) REFERENCES sgo.tb_usuario(id_usuario);

INSERT INTO sgo.tb_usuario (ds_login,ds_senha) VALUES('admin','123456');
